### ISSUE TITLE
Interoperability with other packages

### ISSUE THREAD

**Issue by aarondall** [jchen419/Matroids-M2#1]
**How to improve interoperability with other packages?**

I would like to have the following packages automatically load when I load the `Matroids` package: `HyperplaneArrangements`, `Posets`, `SimplicialComplexes`. This is needed for defining matroids from types defined in those packages. I try to load them by listing them in the `PackageImports` key in the option table of the package as follows

	newPackage(
		"Matroids",
		Headline => "A package for working with matroids in Macaulay2",
		Version => "0.2",
		Date => "July 1, 2015",
		Authors => {{Name => "Justin Chen"}},
		DebuggingMode => true,
		HomePage => "https://github.com/jchen419/Matroids-M2",
		PackageImports => {
			"Graphs",
			"HyperplaneArrangements",
			"Poset",
			"SimplicialComplexes"
	        }
	)

Trying to reload the `Matroids` package with this modification throws errors of the form

	error: assignment to protected built-in global variable 'circuits'

because there are conflicts between methods defined in `Matroids` and those in the other packages. These conflicts include:

 1. methods defined in `Matroids` and `HyperplaneArrangements`
 	* `circuits`
 	* `closure`
 	* `flats`
 	* `restriction`
 	* `deletion`
 2. methods defined in `Matroids` and `Posets`
 	* `tuttePolynomial`

What is the best way to resolve these conflicts?

One possibility is to change the names of the above methods in `Matroids` to something like `matroidCircuits` or some such. Advantages of doing this are

 * resolve the conflict by making method names unique
 * names remind users to apply matroid methods only to matroids and not to other types

The downside, of course, is that quite a lot of code editing would need to be done.

Another option is not to export these symbols again and simply to build on the methods already in place in the other packages. For example, for the `circuits` method one need only comment out two lines of code, one in the `export` list

	export {
		"Matroid",
		...
		-- "circuits",
		...
		}

and the other when the `circuits` method is defined

	--circuits = method()
	circuits Matroid := List => M -> (...)

This will also resolve the conflicts and has the advantage of being minimally invasive to code. There are (at least) three drawbacks. One is that this approach doesn't seem to work if the method in `Matroids` has a nontrivial option table (see, e.g., `closure`). Another is that the user will have to be mindful about the type used as an argument for these methods because the outputs can have different structures.

	i1 : circuits typeA 3

	o1 = {{3, 4, 5}, {1, 2, 5}, {0, 2, 4}, {0, 1, 3}, {0, 1, 4, 5}, {0, 2, 3, 5}, {1, 2, 3, 4}}

	i2 : circuits matroid completeGraph 4

	o2 = {set {0, 1, 3}, set {0, 2, 4}, set {1, 2, 5}, set {0, 2, 3, 5}, set {0, 1, 4, 5}, set {1, 2, 3, 4}, set {3, 4, 5}}

Another drawback occurs when accessing the documentation. Calling `help circuits` under this set-up gives information on the `HyperplaneArrangements` method. To view the documentation for the `Matroids` method one has to call `help Matroids$circuits`.

So, back to the question from the top: What is the best way to get `Matroids` to play well with other related packages?

**Comment by jchen419** [comment]
So the approach I've decided to take is to overload methods as much as possible (which means exporting as few new symbols as possible). For instance `tuttePolynomial` is no longer exported, but `Matroids` defines an option for `tuttePolynomial(Matroid)`, overloading the existing method for `tuttePolynomial` in `Posets`. 

Currently `Matroids` lists `Polyhedra`, `Graphs`, and `Posets` under `PackageImports` (and `PackageExports`), and should be interoperable with these (note however that e.g. `Polyhedra` is itself not completely interoperable with `SimplicialComplexes`, which is loaded by `Graphs`: e.g. both attempt to export `vertices` and `faces`. This leads to warnings on newer versions of Macaulay2, and on older versions the previous package exports will be silently overridden, leading to unexpected behavior).

For `HyperplaneArrangements`, my personal opinion is that `Matroids` will strictly supersede the functionality in common: i.e. `HyperplaneArrangements` should import `Matroids` (rather than the other way around). So to keep with the convention above, `HyperplaneArrangements` should be edited to not export the method names in common.
