### ISSUE TITLE
Bug: dualMatroid

### ISSUE THREAD

**Issue by aarondall** [jchen419/Matroids-M2#2]
The method `dualMatroid` uses both `groundSet M` and `M.ground`. This leads to some bad behavior if M.groundSet is a set of integers different from `0..n` for some `n`. Here's the code.

> dualMatroid Matroid := Matroid => M -> matroid(groundSet M, (bases M)/(b -> M.ground - b))

One type of bad behavior is that the sum of the ranks of the primal and dual will not equal the size of the ground set.

> i1 : M = matroid {{1,2}};
>
> i2 : N = dualMatroid M;
>
> i3 : peek N
>
>o3 = Matroid{bases => {set {0}}   }
>                      cache => CacheTable{}
>                     ground => set {0, 1}
>                     groundSet => {1, 2}

Another type of bad behavior is that the dual matroid may not be valid.

> i1 : B = {{1, 2}, {2, 3}, {1, 4}, {3, 4}};
>
> i2 : M = matroid B;
>
> i3 : isValid M
>
> o3 = true
>
> i4 : isValid dualMatroid M
>
> o4 = false
>
> i5 : peek dualMatroid M
>
> o5 = Matroid{bases => {set {0, 3}, set {0, 1}, set {0, 2, 3}, set {0, 1, 2}}}
>                       cache => CacheTable{}
>                       ground => set {0, 1, 2, 3}
>                      groundSet => {1, 2, 3, 4}

The following code simply replaces `M.ground` with `M.groundSet` and seems to resolve the issue.

> dualMatroid Matroid := Matroid => M -> (matroid (groundSet M, (bases M)/(b -> M.groundSet - b)))

**Comment by jchen419** [comment]
Hi Aaron, 

Thanks for bringing this to my attention! I believe the issue is actually not with `dualMatroid` (which really should use both `M.ground` and `M.groundSet`). Instead, the issue is in the constructor method - it was actually not always converting the list of bases to their indices in `{0, ..., n-1}`. So the method 

> matroid (List, List) := Matroid => opts -> (E, B) -> (
>      if #B > 0 and not instance(B#0, Set) then B = B/(l -> set l);
>      ...

should be updated to say 

> matroid (List, List) := Matroid => opts -> (E, B) -> (
>      if #B > 0 and not instance(B#0, Set) then B = B/(l -> set indicesOf(E, l));
>      ...

With this change, both your examples seem to be fine. The point is that bases should always be internally represented by their indices in the ground set, with indexing starting at 0 (i.e. if the ground set is `{a, -2, {3,4}, x}`, then a basis element `{-2, x}` is thought of as `{1, 3}`).

I will push a new version of the package to GitHub soon, incorporating this change as well as many others, including some renaming of methods: e.g. `dualMatroid -> dual`, `isValid -> isWellDefined` and `directsum -> ++`.
